trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: "Compilación"
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Proyecto_lenguajes'
    
- task: DotNetCoreCLI@2
  displayName: "Publicación"
  inputs:
    command: 'publish'
    publishWebProjects: true
    workingDirectory: '$(System.DefaultWorkingDirectory)/Proyecto_lenguajes'

- task: AzureRmWebAppDeployment@5
  displayName: "Despliegue"
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(f5346de4-af56-4396-a0e4-188bce1d0bcb)'
    appType: 'webApp'
    WebAppName: 'PortalStudent'
    packageForLinux: '$(System.DefaultWorkingDirectory)//*.zip'
